cursor #cad3f5
cursor_text_color #a5adcb

foreground            #cad3f5
background            #24273a
selection_foreground  #24273a
selection_background  #b7bdf8
url_color             #c6a0f6

color0   #1e2030
color1   #ff728c
color2   #7bf696
color3   #ffdb72
color4   #b287e9
color5   #492871
color6   #c6a0f6
color7   #f6efff
color8   #99939f
color9   #ff9fb1
color10  #a5ffb9
color11  #ffe8a5
color12  #d4b3ff
color13  #dcc0ff
color14  #e8d6ff
color15  #fbf8ff
