# Gaps
$workspaceGaps = 10
$windowGapsIn = 7
$windowGapsOut = 7
$singleWindowGapsOut = 5
# Window styling
$windowOpacity = 1
$windowRounding = 10

$shadowColour = rgba($surfaced4)

$activeWindowBorderColour = rgba($primarye6)
$inactiveWindowBorderColour = rgba($onSurfaceVariant11)

##! KEYBINDS
# Workspaces
$kbMoveWinToWs = Super+Alt
$kbMoveWinToWsGroup = Ctrl+Super+Alt
$kbGoToWs = Super
$kbGoToWsGroup = Ctrl+Super

# Scrolls
$kbScrollPlusCol = Super, period
$kbScrollMinCol = Super, comma
$kbScrollSwapL = Super+Alt, comma
$kbScrollSwapR = Super+Alt, period

$kbNextWs = Ctrl+Super, right
$kbPrevWs = Ctrl+Super, left

$kbToggleSpecialWs = Super, S

# Window groups
$kbWindowGroupCycleNext = Alt, Tab
$kbWindowGroupCyclePrev = Shift+Alt, Tab
$kbUngroup = Super, U
$kbToggleGroup = Super, Backslash
# Window actions
$kbMoveWindow = Super, Z
$kbResizeWindow = Super, X
$kbWindowPip = Super+Alt, Backslash
$kbPinWindow = Super, P
$kbWindowFullscreen = Super, F
$kbWindowBorderedFullscreen = Super+Alt, F
$kbToggleWindowFloating = Super+Alt, Space
$kbCloseWindow = Super, Q

# Apps
$kbSystemMonitor = Ctrl+Shift, Escape
$kbMusic = Super, S
$kbCommunication = Super, D
$kbTodo = Super, G
$kbSteam = Super, R

# Misc
$kbSession = Ctrl+Alt, Delete
$kbClearNotifs = Ctrl+Alt, C
$kbShowPanels = Super, K
$kbLock = Super, L
$kbRestoreLock = Super+Alt, L
