# Bar, wallpaper
exec-once = ~/.config/hypr/hyprland/scripts/start_geoclue_agent.sh

# Input method
# exec-once = fcitx5

# Core components (authentication, lock screen, notification daemon)
# exec-once = hypridle
exec-once = dbus-update-activation-environment --all
exec-once = sleep 1 && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # Some fix idk
exec-once = hyprpm reload

# Clipboard history
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Cursor
$cursorTheme = Bibata-Modern-Classic
$cursorSize = 24
exec-once = hyprctl setcursor $cursorTheme $cursorSize
exec-once = gsettings set org.gnome.desktop.interface cursor-theme '$cursorTheme'
exec-once = gsettings set org.gnome.desktop.interface cursor-size $cursorSize

exec-once = fcitx5 -d
# exec-once = caelestia resizer -d
# exec-once = caelestia shell -d
exec-once = qs -c screenshotTool -d # custom screenshotTool
exec-once = dms run -d
# exec-once = dsearch index sync
exec-once = dsearch serve

# daily usage app
exec-once = [workspace 1]zen-browser
exec-once = [workspace special:communication silent]discord
exec-once = [workspace special:music silent]feishin
exec-once = [workspace special:steam silent]vk_xwayland_wait_ready=false steam
