# MONITOR CONFIG
monitor = HDMI-A-1, modeline 424.08 1920 1928 1960 2000 1080 1164 1172 1178 +hsync -vsync, 0x0, 1, bitdepth, 10
# monitor=,addreserved, 0, 0, 0, 0 # Custom reserved area

# HDMI port: mirror display. To see device name, use `hyprctl monitors`
# monitor=HDMI-A-1,1920x1080@60,1920x0,1,mirror,eDP-1
general {
  # Gaps and border
  gaps_in = 2
  gaps_out = 3
  gaps_workspaces = 50

  border_size = 1
  col.active_border = $activeWindowBorderColour
  col.inactive_border = $inactiveWindowBorderColour
  resize_on_border = true

  no_focus_fallback = true

  allow_tearing = true # This just allows the `immediate` window rule to work

  layout = scrolling

  snap {
    enabled = true
    window_gap = 2
    monitor_gap = 3
    respect_gaps = true
  } 
} 

dwindle {
  pseudotile = true
  preserve_split = true
  smart_split = false
  smart_resizing = true
  # precise_mouse_move = true
} 

master {
  new_status = slave
}

scrolling {
    fullscreen_on_one_column = true
    column_width = 1
    direction = down
}
