# ### hy3 ###
unbind = Super, left
unbind = Super, right
unbind = Super, up
unbind = Super, down

unbind = Super, h
unbind = Super, l
unbind = Super, k
unbind = Super, j

unbind = $kbWindowGroupCycleNext
unbind = $kbWindowGroupCyclePrev
unbind = $kbToggleGroup
unbind = $kbUngroup
unbind = Super+Shift, Comma

bind = Super, left, hy3:movefocus, l
bind = Super, right, hy3:movefocus, r
bind = Super, up, hy3:movefocus, u
bind = Super, down, hy3:movefocus, d
bind = Super, h, hy3:movewindow, l
bind = Super, l, hy3:movewindow, r
bind = Super, k, hy3:movewindow, u
bind = Super, j, hy3:movewindow, d

# ### hy3 tabs ###
# $makegroup = ~/.config/hypr/hyprland/scripts/hy3makegroup.sh # temporary fix until a patch is released
# bind = $kbToggleGroup, exec, $makegroup 
# bind = $kbUngroup, hy3:changegroup, toggletab
bind = $kbToggleGroup, hy3:changegroup, toggletab
bind = $kbWindowGroupCycleNext, hy3:focustab, r, prioritize_hovered, wrap
bind = $kbWindowGroupCyclePrev, hy3:focustab, l, prioritize_hovered, wrap
bind = Super+Shift, Comma, hy3:locktab 
