misc {
  disable_hyprland_logo = true
  disable_splash_rendering = true
  vfr = 1
  # variable refresh rate (freesync)
  vrr = 0 
  mouse_move_enables_dpms = true
  key_press_enables_dpms = true
  animate_manual_resizes = false
  animate_mouse_windowdragging = false
  on_focus_under_fullscreen = 2
  allow_session_lock_restore = true
  session_lock_xray = true
  initial_workspace_tracking = false
  focus_on_activate = true
  force_default_wallpaper = 0
  middle_click_paste = false

  # app not responding
  enable_anr_dialog = false

  background_color = rgb($surfaceContainer)
} 

debug {
  error_position = 1
} 
