plugin {
  hy3 {
    # disable gaps when only one window is onscreen
    # 0 - always show gaps
    # 1 - hide gaps with a single window onscreen
    # 2 - 1 but also show the window border
    no_gaps_when_only = 0 # default: 0

    # policy controlling what happens when a node is removed from a group,
    # leaving only a group
    # 0 = remove the nested group
    # 1 = keep the nested group
    # 2 = keep the nested group only if its parent is a tab group
    node_collapse_policy = 2 # default: 2

    # offset from group split direction when only one window is in a group
    group_inset = 10 # default: 10

    # if a tab group will automatically be created for the first window spawned in a workspace
    tab_first_window = false

    # tab group settings
    tabs {
      # height of the tab bar
      height = 22 # default: 22

      # padding between the tab bar and its focused node
      padding = 4 # default: 6

      # the tab bar should animate in/out from the top instead of below the window
      from_top = true # default: false

      # radius of tab bar corners
      radius = 10 # default: 6

      # tab bar border width
      border_width = 1 # default: 2

      # render the window title on the bar
      render_text = true # default: true

      # center the window title
      text_center = true # default: true

      # font to render the window title with
      text_font = JetBrains Mono NF # default: Sans

      # height of the window title
      text_height = 10 # default: 8

      # left padding of the window title
      # text_padding = <int> # default: 3

      # active tab bar segment colors
      col.active = rgba($primaryd4) # default: rgba(33ccff40)
      col.active.border = rgba($onPrimaryd4) # default: rgba(33ccffee)
      # col.active.text = rgba(ffffffff) # default: rgba(ffffffff)

      # active tab bar segment colors for bars on an unfocused monitor
      col.active_alt_monitor = rgba($primaryd4) # default: rgba(60606040)
      col.active_alt_monitor.border = rgba($onPrimaryd4) # default: rgba(808080ee)
      # col.active_alt_monitor.text = rgba(ffffffff) # default: rgba(ffffffff)

      # focused tab bar segment colors (focused node in unfocused container)
      col.focused = rgba($primaryd4) # default: rgba(60606040)
      col.focused.border = rgba($onPrimaryd4) # default: rgba(808080ee)
      # col.focused.text = rgba(ffffffff) # default: rgba(ffffffff)

      # inactive tab bar segment colors
      col.inactive = rgba($outlined4) # default: rgba(30303020)
      col.inactive.border = rgba($onPrimaryd4) # default: rgba(606060aa)
      # col.inactive.text = rgba(ffffffff) # default: rgba(ffffffff)

      # urgent tab bar segment colors
      col.urgent = rgba($errord4) # default: rgba(ff223340)
      col.urgent.border = rgba($onPrimaryd4) # default: rgba(ff2233ee)
      # col.urgent.text = rgba(ffffffff) # default: rgba(ffffffff)

      # urgent tab bar segment colors
      col.locked = rgba($outlineVariantd4) # default: rgba(90903340)
      col.locked.border = rgba($onPrimaryd4) # default: rgba(909033ee)
      # col.locked.text = rgba(ffffffff) # default: rgba(ffffffff)

      # if tab backgrounds should be blurred
      # Blur is only visible when the above colors are not opaque.
      blur = true # default: true

      # opacity multiplier for tabs
      # Applies to blur as well as the given colors.
      opacity = 0.95 # default: 1.0
    }

    # autotiling settings
    autotile {
      # enable autotile
      enable = true # default: false

      # make autotile-created groups ephemeral
      ephemeral_groups = true # default: true

      # if a window would be squished smaller than this width, a vertical split will be created
      # -1 = never automatically split vertically
      # 0 = always automatically split vertically
      # <number> = pixel width to split at
      trigger_width = 0 # default: 0
    }
  }
}
