[[mgr.prepend_keymap]]
on = ["g", "l"]
run = "cd ~/.local"
desc = "Go ~/.local"

[[mgr.prepend_keymap]]
on = ["g", "m"]
run = "cd /run/media"
desc = "Go mount points"

[[mgr.prepend_keymap]]
on = ["g", "t"]
run = "cd ~/.local/share/Trash/files/"
desc = "Go trash"

[[mgr.prepend_keymap]]
on = "u"
run = "plugin restore"
desc = "Restore last deleted files/folders"

[[mgr.prepend_keymap]]
on = "U"
run = "plugin restore -- --interactive"
desc = "Restore deleted files/folders (Interactive)"

[[mgr.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = ["<Enter>"]
run = "plugin smart-enter"
desc = "Enter the child directory, or open the selected file"

[[mgr.prepend_keymap]]
on = ["<Backspace>"]
run = "leave"
desc = "Go back to the parent directory"

[[mgr.prepend_keymap]]
on = "<C-e>"
run = "seek 5"

[[mgr.prepend_keymap]]
# glow.yazi <C-e>, <C-y>
on = "<C-y>"
run = "seek -5"

[[mgr.prepend_keymap]]
on = "T"
run = "shell -- nohup kitty > /dev/null 2>&1 &"
desc = "Run kitty detached"

[[mgr.prepend_keymap]]
on = "<S-f4>"
run = "shell -- nohup kitty > /dev/null 2>&1 &"
desc = "Run kitty detached"

[[mgr.prepend_keymap]]
on = "M"
run = "plugin mount"

[[mgr.prepend_keymap]]
on = "y"
run = [
  'shell -- for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list',
  "yank"
]

[[mgr.prepend_keymap]]
on = "<f2>"
run = "rename"
desc = "Rename file or directory"

[[mgr.prepend_keymap]]
on = "<S-Enter>"
run = 'shell -- dms open "$@"'
desc = "Select to open with"

[[mgr.prepend_keymap]]
on = ["c", "a", "a"]
run = "plugin compress"
desc = "Archive selected files"

[[mgr.prepend_keymap]]
on = ["c", "a", "p"]
run = "plugin compress -p"
desc = "Archive selected files (password)"

[[mgr.prepend_keymap]]
on = ["c", "a", "l"]
run = "plugin compress -l"
desc = "Archive selected files (compression level)"

[[mgr.prepend_keymap]]
on = ["c", "m"]
run = "plugin chmod"
desc = "Chmod on selected files"

[[mgr.prepend_keymap]]
on = "!"
for = "unix"
run = 'shell "$SHELL" --block'
desc = "Open $SHELL here"

[[mgr.prepend_keymap]]
on = "<C-n>"
run = "shell -- dragon-drop -x -i -T %s1"
desc = "dragon-drop drag-drop"

# [[mgr.prepend_keymap]]
# on = "p"
# run = "plugin smart-paste"
# desc = "Paste into the hovered directory or CWD"
